name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t your-docker-repo/image-name:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-docker-repo/image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Docker host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_SSH_USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          script: |
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker pull your-docker-repo/image-name:latest
            docker run -d -p 80:80 --name your-container-name your-docker-repo/image-name:latest
